[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "https://khelifi-salmen.com/*"
  to = "https://www.khelifi-salmen.com/:splat"
  status = 301
  force = true
